version: "3.7"
services: # 講述有幾個service 底下為 postgresSQL 跟 pgadmin
    db: # 將postgresSQL叫做 db
        image: postgres:latest # 告訴這個基於哪個image (OO概念 image就很像Class 要透過image建立container)
        restart: always # 遇到error要不要重啟
        environment: # 有關於postgresSQL的設定(要去看docker官網)
            POSTGRES_DB: postgres
            POSTGRES_USER: user
            POSTGRES_PASSWORD: 1234
            PGDATA: /var/lib/postgresql/data
        volumes: # docker 相關資料放的位置
            - db-data:/var/lib/postgresql/data
        ports: # 開啟port端（對內對外的）
            - "5432:5432"
    pgadmin: # 以下類推
        image: dpage/pgadmin4:latest
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: yitingwu.1030@gmail.com
            PGADMIN_DEFAULT_PASSWORD: 1234
            PGADMIN_LISTEN_PORT: 80
        ports:
            - "8080:80"
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        links:
            - "db:pgsql-server"
volumes:
    db-data:
    pgadmin-data: